# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepermission',
            name='can_read',
            field=models.SmallIntegerField(blank=True, choices=[(1, '\u5141\u8bb8'), (0, '\u62d2\u7edd')], default=True, null=True, verbose_name='\u8bfb'),
        ),
    ]
