# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-11 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0002_auto_20171008_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filepermission',
            options={'verbose_name': '\u89d2\u8272', 'verbose_name_plural': '\u89d2\u8272'},
        ),
    ]
