# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-02 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0003_auto_20171011_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ('name',), 'permissions': (('can_use_directory_listing', 'Can use directory listing'),), 'verbose_name': 'Folder', 'verbose_name_plural': '\u4f20\u7f8e\u77e5\u8bc6\u5e93'},
        ),
        migrations.AlterField(
            model_name='file',
            name='perm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.FilePermission', verbose_name='\u89d2\u8272'),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='filer_owned_folders', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
